name: build image
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  web:
    uses: csmith/github-workflows/.github/workflows/build-image.yml@master
    secrets: inherit
    dockerfile: web.Dockerfile
    image: kowalski/web

  discord:
    uses: csmith/github-workflows/.github/workflows/build-image.yml@master
    secrets: inherit
    dockerfile: discord.Dockerfile
    image: kowalski/discord
