name: build image
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  web:
    uses: csmith/github-workflows/.github/workflows/build-image.yml@master
    secrets: inherit
    with:
      dockerfile: web.Dockerfile
      image: csmith/kowalski/web

  discord:
    uses: csmith/github-workflows/.github/workflows/build-image.yml@master
    secrets: inherit
    with:
      dockerfile: discord.Dockerfile
      image: csmith/kowalski/discord
